package id.co.map.spk.enums;

public enum SpkStatus {

    SUBMITTED,
    UPDATED,
    CANCELED,
    APPROVED,
    DONE_APPROVED,
    REJECTED,
    VERIFIED,
    INTERNAL_ORDER_CREATED,
    INTERNAL_ORDER_FAILED,
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_FAILED,
    GR1,
    GR2,
    GR3,
    GR4,
    GR5,
    TOP_FAILED,
    CLOSE_REQUEST,
    CLOSE_APPROVED,
    CLOSED,
    COMPLETED,
    NEED_TO_CLOSE,
    UPDATE_ASSET_CLASS_ID,
    CLOSE_INTERNAL_ORDER,
    INTERNAL_ORDER_CLOSE_FAILED
}
